export * from './AdminPage'
export * from './HomePage'
export * from './LoginPage'
export * from './CartPage'
export * from './ProductPage'
export * from './CheckoutPage'
export * from './AccountPage'
export * from './ShopPage'
export * from './For clients/index'
export * from './CategoryPage'
export * from './TypePage'