export * from './AdminPage'
export * from './HomePage'
export * from './AuthPage'
export * from './ProductPage'
export * from './CheckoutPage'
export * from './AccountPage'
export * from './ShopPage'
export * from './For clients/index'
export * from './CategoryPage'
export * from './TypePage'
export * from './AccountPage'
export * from './CompleteOrderPage'
export * from './SetNewPasswordPage'
export * from './ForgotPasswordPage'
export * from './ErrorPage'