export * from './category.slice'
export * from './product.slice'
export * from './type.slice'
export * from './product.slice'
export * from './auth.slice'
export * from './basket.slice'
export * from './user.slice'